=== AndreyNed/jd1_homework/BookDB/xml_docs/library_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/librarySchema"
	xmlns:tns="http://www.it-academy.by/librarySchema"
	elementFormDefault="qualified">
	
	<xs:element name="books" type="tns:books_type"/>
	
	<xs:complexType name="books_type">
		<xs:sequence>
			<xs:element name="book" type="tns:book_type" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="book_type">
		<xs:sequence>
			<xs:element name="isbn" type="tns:isbn_type" minOccurs="0" />
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="author" type="tns:author_type" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>
	
	<xs:complexType name="author_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="date-of-birth" type="xs:date" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="isbn_type">
		<xs:attribute name="number" type="xs:string" />
	</xs:complexType>
	
</xs:schema>

=== AndreyNed/jd1_homework/BookDB/xml_docs/library.xml
<?xml version="1.0" encoding="UTF-8"?>



<books xmlns="http://www.it-academy.by/librarySchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.it-academy.by/librarySchema library_schema.xsd">
	<book id="1">
		<isbn number="0000" />
		<title>
			Book1
		</title>
		<pages>
			10
		</pages>
		<author>
			<name>
				Author1
			</name>
			<date-of-birth>
				1962-11-07
			</date-of-birth>
		</author>
		<author>
			<name>
				Author11
			</name>
			<date-of-birth>
				1960-11-07
			</date-of-birth>
		</author>
	</book>
	
	<book id="2">
		<isbn number="0001" />
		<title>
			Book2
		</title>
		<pages>
			20
		</pages>
		<author>
			<name>
				Author2
			</name>
			<date-of-birth>
				1965-06-24
			</date-of-birth>
		</author>
	</book>
	
	<book id="3">
		<isbn number="0003" />
		<title>
			Book3
		</title>
		<pages>
			50
		</pages>
		<author>
			<name>
				Author3
			</name>
			<date-of-birth>
				1974-12-07
			</date-of-birth>
		</author>
	</book>
	
	<book id="4">
		<isbn number="0004" />
		<title>
			Book3
		</title>
		<pages>
			50
		</pages>
		<author>
			<name>
				Author3
			</name>
			<date-of-birth>
				1974-12-07
			</date-of-birth>
		</author>
	</book>
</books>
